### ISSUE TITLE
new g++ compilation

### ISSUE THREAD

**Issue by flammie** [moses-smt/salm#1]
The code doesn't compile out of the box with gcc-6.4.0 anymore, I had to change the fstream==NULL comparisons to (!fstream), based on https://stackoverflow.com/questions/32589155/stdofstream-null-wont-compile-for-std-gnu11-any-workaround

**Comment by hieuhoang** [comment]
please create a pull request so others won't trip over it

**Comment by hieuhoang** [comment]
fixed https://github.com/moses-smt/salm/pull/2
