### ISSUE TITLE
SampleNGramIns.O32 needed

### ISSUE THREAD

**Issue by s4d3** [moses-smt/salm#3]
Hi,

I try to install SALM but I got following error:
make: *** No rule to make target '../../Bin/Linux/Search/SampleNGramIns.O32', needed by 'allO32'.

I'am using Linux Ubuntu 16.04 LTS 32 bit on Virtual Box. 

Can you help me?

**Comment by hieuhoang** [comment]
i haven't used the 32-bit version for a long time and I'm not sure if it works. I don't think there is any difference anyway

**Comment by s4d3** [comment]
I change to 62-bit version and it works.
